[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "CI=false NODE_OPTIONS='--max_old_space_size=4096' npm run build"
  publish = "build"
  functions = "netlify/functions"
